name: Build VyOS image with dae

on:
  workflow_dispatch:
    inputs:
      dae_version:
        description: dae release tag, or latest
        required: true
        default: latest
        type: string

jobs:
  build:
    uses: ./.github/workflows/_build-custom-vyos.yml
    with:
      include_dae: true
      dae_version: ${{ inputs.dae_version }}
      artifact_name: vyos-with-dae-amd64
      iso_name: vyos-with-dae-amd64.iso
      version_label: with-dae
