name: Build VyOS dae-ready image

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-custom-vyos.yml
    with:
      include_dae: false
      artifact_name: vyos-dae-ready-amd64
      iso_name: vyos-dae-ready-amd64.iso
      version_label: dae-ready
